### PR TITLE
add(pattern): action panel

### PR DESCRIPTION
**Pull request by deepakgithub11**
This pr adds new pattern for "Action Panel"

### CODE REVIEW

**Comment by ajitbohra** [comment]
code view is not working

**Comment by deepakgithub11** [comment]
> code view is not working

noted

**Comment by ajitbohra** [comment]
remove the add channel dropdown and grey background and padding

**Comment by deepakgithub11** [comment]
required changes applied 
for now i have kept new-patterns thumbnail as blank

**Pull request closed without merging**
